### ISSUE TITLE
Add example to follow training with a GUI

### ISSUE THREAD

**Issue by asyd** [cgarciae/cybrain#6]
If it's possible could add an example to visualize (like using qt app) the network and follow its training?

Thanks

**Comment by cgarciae** [comment]
Would certainly be nice, but there are more basic stuff to resolve first like more trainers, more layers, more tests, and so on.

**Comment by asyd** [comment]
Sure indeed. Note I can help, especially on the GUI part, and I added it as RFE, even if it's in 6 months :)
