### ISSUE TITLE
how to contact you Cristian Garcia?

### ISSUE THREAD

**Issue by simonli1229** [cgarciae/cybrain#7]
my email is honggang.li@makercollider.com

**Comment by cgarciae** [comment]
@simonli1229 my email is cgarcia.e88@gmail.com

**Comment by simonli1229** [comment]
Hi Cristian,

I see you are a mathematical developer, very glad to know u.

How are you now? 

Do u have plan to go to China?

发自我的 iPhone

**Comment by cgarciae** [comment]
I'll write you an email. Closing the issue.
